name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run CLI Integration Tests
      run: cargo test --test cli_tests --verbose
    - name: Run Other Unit Tests
      run: cargo test --lib --verbose
